### ISSUE TITLE
提示Code已损坏，请重新安装

### ISSUE THREAD

**Issue by mnyon** [noterpopo/vscode-live2d#2]
报错提示：Code已损坏，请重新安装
影响：似乎会引起部分侧边栏图标不能正常显示

非常Nice的插件，期待作者更新修复

**Comment by noterpopo** [comment]
插件实现的原理是修改vscode中的一个js文件（添加了一些代码），vscode启动校验时会提示code损坏，这个对功能和安全不会造成影响。需要找到另外的方法注入js代码才能避免这个提示，作者尽量修复

**Comment by noterpopo** [comment]
> 报错提示：Code已损坏，请重新安装
> 影响：似乎会引起部分侧边栏图标不能正常显示
> 
> 非常Nice的插件，期待作者更新修复

网上找到一个关掉提示的方法->https://blog.csdn.net/qq_29339467/article/details/104738160
安装后暂时不会出现侧边栏图标不能正常显示的问题

**Comment by noterpopo** [comment]
最新版本的插件已经修复这个问题
